name: Build xtrail

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential xorg-dev

      - name: Build executable
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: xtrail-executable
          path: ./xtrail
          if-no-files-found: error
